### ISSUE TITLE
Check logic for choosing front page content colour (inconsistent behaviour across pages)

### ISSUE THREAD

**Issue by EnnoKirsimae** [Voog/design-firenze#84]
The logic deciding whether content on a front page layout is light or dark can give different results for two identical states on different pages (possibly dependant on previous saved states). 
Specifically, on a client's page the content would be rendered in black if a fully transparent background (or no background) was chosen from the background colour picker even though the underlying background image was dark. Using the same background image and choosing a fully transparent background colour from the colour picker did not yield the same results on a test page.
Overall, manipulating the background colour's opacity and brightness, I could make the appearing image much brighter on the test page before the content would be rendered in black.

**Comment by kaspar-naaber** [comment]
Scheme calculation didn't use the default image's dominant color.
