### ISSUE TITLE
Content area currentColor bugs

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-firenze#90]
(Pull request: #92)

Related with Edicy/edicy_cms#1755
- [x] Dark background. Default components (without content) don't get changed color. Video: http://recordit.co/yptR0Cglck

@kaspar-naaber: Fixed for standard templates. For customized templates it is an easy manual fix if anyone requests it.

**Comment by kaspar-naaber** [comment]
Can be closed/merged after mergeing Edicy/edicy_cms#1755
